databases:
  - name: nycnoise
    plan: starter
    region: ohio
services:
  - type: web
    plan: starter
    numInstances: 1
    name: nycnoise
    env: python
    region: ohio
    buildCommand: "./bin/build.sh"
    startCommand: 'gunicorn --access-logformat ''%(h)s %(l)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" reqtime: %(M)s ms'' nycnoise.wsgi:application'
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nycnoise
          property: connectionString
      - key: ALLOWED_HOSTS
        # render.com is broken for saving environment variables on launch day???? FIXME
        # render.com is broken for saving environment variables on launch day???? FIXME
        # render.com is broken for saving environment variables on launch day???? FIXME
        value: nycnoise.onrender.com,nyc-noise.com
      - key: DJANGO_SETTINGS_MODULE
        sync: false
