# Generated by Django 4.2.5 on 2023-10-02 19:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(default='event', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
