# Generated by Django 4.2.5 on 2023-10-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_description_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
