# Generated by Django 4.2.5 on 2023-10-02 19:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=100, null=True),
        ),
    ]
