# Generated by Django 4.2.5 on 2023-10-04 20:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True),
        ),
    ]
