# Generated by Django 4.2.5 on 2023-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(auto_now=True, verbose_name='Start date & time'),
        ),
    ]
