# Generated by Django 4.2.5 on 2023-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_event_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='Start time'),
        ),
    ]
