# Generated by Django 4.2.5 on 2023-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_event_starttime"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
