# Generated by Django 4.2.5 on 2023-10-15 19:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_event_starttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
