# Generated by Django 4.2.5 on 2023-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
