# Generated by Django 4.2.5 on 2023-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_venue_options_venue_age_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="neighborhood_and_borough",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
