# Generated by Django 4.2.5 on 2023-10-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_venue_neighborhood_and_borough"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="google_maps_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
