# Generated by Django 4.2.5 on 2023-10-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_event_event_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_link",
            new_name="hyperlink",
        ),
    ]
