# Generated by Django 4.2.5 on 2023-10-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_event_link_event_hyperlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="accessibility_emoji",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="accessibility_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="accessibility_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
