# Generated by Django 4.2.5 on 2023-10-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_datemessage'),
        ('core', '0018_venue_accessibility_emoji_venue_accessibility_link_and_more'),
    ]

    operations = [
    ]
