# Generated by Django 4.2.5 on 2023-10-22 21:06

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_venue_accessibility_emoji_venue_accessibility_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
    ]
