# Generated by Django 4.2.5 on 2023-10-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_venue_options"),
        ("core", "0020_alter_venue_options_alter_venue_location"),
    ]

    operations = []
