# Generated by Django 4.2.5 on 2023-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_merge_20231023_1857"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True, verbose_name="Date")),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
    ]
