# Generated by Django 4.2.5 on 2023-10-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_staticpage_slug_staticpage_url_path"),
        ("core", "0022_datemessage"),
    ]

    operations = []
