# Generated by Django 4.2.5 on 2023-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_datemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="age_policy_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
