# Generated by Django 4.2.5 on 2023-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_event_age_policy_override_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="preface",
            field=models.TextField(blank=True, null=True),
        ),
    ]
