# Generated by Django 4.2.5 on 2023-10-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_event_preface"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="title",
        ),
    ]
