# Generated by Django 4.2.5 on 2023-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_name_event_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="artists",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
