# Generated by Django 4.2.5 on 2023-10-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
