# Generated by Django 4.2.5 on 2023-11-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_merge_20231023_2124"),
        ("core", "0032_rename_location_venue_address"),
    ]

    operations = []
