# Generated by Django 4.2.5 on 2023-11-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_merge_20231106_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="starttime_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
