# Generated by Django 4.2.5 on 2023-11-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_event_starttime_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubcriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
