# Generated by Django 4.2.5 on 2023-11-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_emailsubcriber"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailSubcriber",
            new_name="EmailSubscriber",
        ),
    ]
