# Generated by Django 4.2.5 on 2023-11-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_rename_emailsubcriber_emailsubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_cal_msg", models.TextField(blank=True, null=True)),
                ("post_cal_msg", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Main page messages",
            },
        ),
    ]
