# Generated by Django 4.2.5 on 2023-11-25 17:21

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_rename_emailsubcriber_emailsubscriber"),
    ]

    operations = [
        # install the trigram extension for partial/fuzzy search
        # this is used (right now at least during venue import)
        # but could/should be used for full site search as wel!!
        TrigramExtension(),
    ]
