# Generated by Django 4.2.5 on 2023-11-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_mainmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmessage",
            name="post_cal_msg",
            field=models.TextField(
                blank=True, null=True, verbose_name="Post calendar message"
            ),
        ),
        migrations.AlterField(
            model_name="mainmessage",
            name="pre_cal_msg",
            field=models.TextField(
                blank=True, null=True, verbose_name="Pre calendar message"
            ),
        ),
    ]
