# Generated by Django 4.2.5 on 2023-11-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_auto_20231125_1221"),
        ("core", "0039_rename_mainmessage_indexpagemessages_and_more"),
    ]

    operations = []
