# Generated by Django 4.2.5 on 2023-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_merge_20231125_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="name_the",
            field=models.BooleanField(default=False),
        ),
    ]
