# Generated by Django 4.2.5 on 2023-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="show_in_footer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="show_in_header",
            field=models.BooleanField(default=False),
        ),
    ]
