# Generated by Django 4.2.5 on 2023-12-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_menuitem_show_in_footer_menuitem_show_in_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="same_time_order_override",
            field=models.IntegerField(default=0),
        ),
    ]
