# Generated by Django 4.2.5 on 2023-12-03 21:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_event_same_time_order_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datemessage",
            name="message",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="same_time_order_override",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
    ]
