# Generated by Django 4.2.8 on 2023-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_staticpage_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="starttime",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Start time"
            ),
        ),
    ]
