# Generated by Django 4.2.8 on 2023-12-17 20:39

from django.db import migrations


def rich_textify_venue_override(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    for event in Event.objects.filter(venue_override__isnull=False):
        if event.venue_override:
            event.venue_override = f"<p><b>{event.venue_override}</b></p>"
            event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_event_age_policy_emoji_override"),
    ]

    operations = [
        migrations.RunPython(rich_textify_venue_override),
    ]
