# Generated by Django 4.2.9 on 2024-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_venue_email_venue_phone_venue_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="backline_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="booking_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="capacity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="house_fees",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
