# Generated by Django 4.2.9 on 2024-02-17 18:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_venue_backline_link_venue_booking_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="accessibility_emoji",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="♿️"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="accessibility_notes",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="capacity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="cap"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="house_fees",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="fees"
            ),
        ),
    ]
