# Generated by Django 4.2.9 on 2024-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_venue_accessibility_emoji_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.CharField(
                blank=True,
                choices=[
                    ("🌀", "free-notaflof"),
                    ("$", "$"),
                    ("$$", "$$"),
                    ("$$$", "$$$"),
                    ("$$$$", "$$$$"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
