# Generated by Django 4.2.9 on 2024-02-17 18:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="wage_information",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
