# Generated by Django 4.2.10 on 2024-02-17 19:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_venue_wage_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchableStaticPageBit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_text_extract", models.TextField()),
                (
                    "static_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.staticpage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "content_text_extract", config="english"
                        ),
                        name="search_vector_idx",
                    )
                ],
            },
        ),
    ]
