# Generated by Django 4.2.10 on 2024-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_remove_searchablestaticpagebit_search_vector_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="baked_html_template",
            field=models.TextField(blank=True, null=True),
        ),
    ]
