# Generated by Django 4.2.10 on 2024-02-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_event_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
