# Generated by Django 4.2.10 on 2024-02-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_event_user_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='closed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
