# Generated by Django 4.2.10 on 2024-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_venue_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllEventProxy",
            fields=[],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.event",),
        ),
        migrations.AddField(
            model_name="venue",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
