# Generated by Django 4.2.10 on 2024-03-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_auto_20240302_1439"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="closed",
        ),
    ]
