# Generated by Django 4.2.10 on 2024-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="latitude",
            field=models.FloatField(null=True, verbose_name="latitude"),
        ),
        migrations.AddField(
            model_name="venue",
            name="longitude",
            field=models.FloatField(null=True, verbose_name="longitude"),
        ),
    ]
