# Generated by Django 4.2.17 on 2025-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                help_text="This can either be a full url like https://... OR if it links to an internal page i.e. the greg page, you should enter /greg with the slash!",
                max_length=255,
            ),
        ),
    ]
