# Generated by Django 4.2.10 on 2024-09-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="page_image",
            field=models.FileField(null=True, upload_to="core/static/images/pages"),
        ),
    ]
