# Generated by Django 4.2.17 on 2025-01-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_venue_latitude_venue_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
