# Generated by Django 4.2.17 on 2025-01-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_menuitem_url"),
        ("core", "0071_alter_venue_latitude_alter_venue_longitude"),
    ]

    operations = []
