from .base import *

DEBUG = False

# FIXME render doesn't let us save environment variables on launch day??? why.........
# FIXME render doesn't let us save environment variables on launch day??? why.........
# FIXME render doesn't let us save environment variables on launch day??? why.........
# FIXME render doesn't let us save environment variables on launch day??? why.........
# FIXME render doesn't let us save environment variables on launch day??? why.........
# FIXME render doesn't let us save environment variables on launch day??? why.........
# FIXME render doesn't let us save environment variables on launch day??? why.........
ALLOWED_HOSTS = ["nycnoise.onrender.com", "nyc-noise.com"]

# default logging doesn't log to console with DEBUG=False
# see https://github.com/django/django/blob/main/django/utils/log.py
# override i.e. always log to console
LOGGING["handlers"]["console"] = {
    "class": "logging.StreamHandler",
}
