name: Django CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "main - nycnoise"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DJANGO_SETTINGS_MODULE: ${{ env.DJANGO_SETTINGS_MODULE }}
          RC_DEVELOPER_INTERNAL_TOKEN: ${{ env.RC_DEVELOPER_INTERNAL_TOKEN }}
          PROD_INTERNAL_API_SERVER: ${{ env.PROD_INTERNAL_API_SERVER }}
          DEBUG_TOOLBAR_ENABLE: ${{ env.DEBUG_TOOLBAR_ENABLE }}
          PYINSTRUMENT_ENABLE: ${{ env.PYINSTRUMENT_ENABLE }}
